# Site settings
title: Measurement Book
email: lifidea@gmail.com
description: > # My first book
baseurl: "" # the subpath of your site, e.g. /blog/
url: "http://jin.info" # the base hostname & protocol for your site
twitter_username: lifidea

# Build settings
markdown: kramdown
